name: github_actions_toolkit
description: Utilities for GitHub Actions coded in Dart.
version: 0.0.2
repository: https://github.com/axel-op/dart-github-action

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
