name: github_actions_toolkit
description: Toolkit containing useful methods to build a GitHub Action with Dart.
version: 0.0.5
repository: https://github.com/axel-op/github_actions_toolkit.dart
homepage: https://github.com/axel-op/github_actions_toolkit.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  synchronized: ^2.2.0
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
