name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container: google/dart:2

    steps:
      - uses: actions/checkout@v2
      - name: Run test app
        id: dart-app
        uses: ./test
      - name: Test outputs
        run: |
          if [ -z "${{ steps.dart-app.outputs.time }}" ]
          then
            exit 1
          fi
