name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: google/dart:2

    steps:
      - uses: actions/checkout@v2
      - name: Run test app
        id: dart-app
        uses: ./tool
      - name: Test outputs
        run: |
          if [ -z "${{ steps.dart-app.outputs.time }}" ]
          then
            exit 1
          fi

  publishable:
    runs-on: ubuntu-latest
    container: google/dart:2

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Run dartdoc
        run: dartdoc
      - name: Test pub publish
        run: pub publish --dry-run
