name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container: google/dart:2

    steps:
      - uses: actions/checkout@v2
      - uses: ./example
        with:
          who-to-greet: "you"
